// Code generated by protoc-gen-go. DO NOT EDIT.
// source: market.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type CreateAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{0}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// The response message containing the greetings
type CreateAccountResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{1}
}
func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(dst, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AssetRule struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetRule) Reset()         { *m = AssetRule{} }
func (m *AssetRule) String() string { return proto.CompactTextString(m) }
func (*AssetRule) ProtoMessage()    {}
func (*AssetRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{2}
}
func (m *AssetRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetRule.Unmarshal(m, b)
}
func (m *AssetRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetRule.Marshal(b, m, deterministic)
}
func (dst *AssetRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetRule.Merge(dst, src)
}
func (m *AssetRule) XXX_Size() int {
	return xxx_messageInfo_AssetRule.Size(m)
}
func (m *AssetRule) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetRule.DiscardUnknown(m)
}

var xxx_messageInfo_AssetRule proto.InternalMessageInfo

func (m *AssetRule) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AssetRule) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// The request message containing the user's name.
type CreateAssetRequest struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules                []*AssetRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	PrivateKey           string       `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateAssetRequest) Reset()         { *m = CreateAssetRequest{} }
func (m *CreateAssetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAssetRequest) ProtoMessage()    {}
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{3}
}
func (m *CreateAssetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssetRequest.Unmarshal(m, b)
}
func (m *CreateAssetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssetRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAssetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssetRequest.Merge(dst, src)
}
func (m *CreateAssetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAssetRequest.Size(m)
}
func (m *CreateAssetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssetRequest proto.InternalMessageInfo

func (m *CreateAssetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAssetRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAssetRequest) GetRules() []*AssetRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *CreateAssetRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

// The response message containing the greetings
type CreateAssetResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAssetResponse) Reset()         { *m = CreateAssetResponse{} }
func (m *CreateAssetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAssetResponse) ProtoMessage()    {}
func (*CreateAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{4}
}
func (m *CreateAssetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssetResponse.Unmarshal(m, b)
}
func (m *CreateAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssetResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssetResponse.Merge(dst, src)
}
func (m *CreateAssetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAssetResponse.Size(m)
}
func (m *CreateAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssetResponse proto.InternalMessageInfo

func (m *CreateAssetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the user's name.
type CreateHoldingRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Descrption           string   `protobuf:"bytes,3,opt,name=descrption,proto3" json:"descrption,omitempty"`
	Asset                string   `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Quantity             int64    `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PrivateKey           string   `protobuf:"bytes,6,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHoldingRequest) Reset()         { *m = CreateHoldingRequest{} }
func (m *CreateHoldingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHoldingRequest) ProtoMessage()    {}
func (*CreateHoldingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{5}
}
func (m *CreateHoldingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHoldingRequest.Unmarshal(m, b)
}
func (m *CreateHoldingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHoldingRequest.Marshal(b, m, deterministic)
}
func (dst *CreateHoldingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHoldingRequest.Merge(dst, src)
}
func (m *CreateHoldingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHoldingRequest.Size(m)
}
func (m *CreateHoldingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHoldingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHoldingRequest proto.InternalMessageInfo

func (m *CreateHoldingRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *CreateHoldingRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *CreateHoldingRequest) GetDescrption() string {
	if m != nil {
		return m.Descrption
	}
	return ""
}

func (m *CreateHoldingRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *CreateHoldingRequest) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *CreateHoldingRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

// The response message containing the greetings
type CreateHoldingResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHoldingResponse) Reset()         { *m = CreateHoldingResponse{} }
func (m *CreateHoldingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHoldingResponse) ProtoMessage()    {}
func (*CreateHoldingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{6}
}
func (m *CreateHoldingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHoldingResponse.Unmarshal(m, b)
}
func (m *CreateHoldingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHoldingResponse.Marshal(b, m, deterministic)
}
func (dst *CreateHoldingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHoldingResponse.Merge(dst, src)
}
func (m *CreateHoldingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHoldingResponse.Size(m)
}
func (m *CreateHoldingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHoldingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHoldingResponse proto.InternalMessageInfo

func (m *CreateHoldingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MarketplaceHolding struct {
	HoldingId            string   `protobuf:"bytes,1,opt,name=holdingId,proto3" json:"holdingId,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Asset                string   `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketplaceHolding) Reset()         { *m = MarketplaceHolding{} }
func (m *MarketplaceHolding) String() string { return proto.CompactTextString(m) }
func (*MarketplaceHolding) ProtoMessage()    {}
func (*MarketplaceHolding) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{7}
}
func (m *MarketplaceHolding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketplaceHolding.Unmarshal(m, b)
}
func (m *MarketplaceHolding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketplaceHolding.Marshal(b, m, deterministic)
}
func (dst *MarketplaceHolding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketplaceHolding.Merge(dst, src)
}
func (m *MarketplaceHolding) XXX_Size() int {
	return xxx_messageInfo_MarketplaceHolding.Size(m)
}
func (m *MarketplaceHolding) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketplaceHolding.DiscardUnknown(m)
}

var xxx_messageInfo_MarketplaceHolding proto.InternalMessageInfo

func (m *MarketplaceHolding) GetHoldingId() string {
	if m != nil {
		return m.HoldingId
	}
	return ""
}

func (m *MarketplaceHolding) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *MarketplaceHolding) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type OfferParticipant struct {
	SrcHolding           string   `protobuf:"bytes,1,opt,name=SrcHolding,proto3" json:"SrcHolding,omitempty"`
	TargetHolding        string   `protobuf:"bytes,2,opt,name=TargetHolding,proto3" json:"TargetHolding,omitempty"`
	SrcAsset             string   `protobuf:"bytes,3,opt,name=SrcAsset,proto3" json:"SrcAsset,omitempty"`
	TargetAsset          string   `protobuf:"bytes,4,opt,name=TargetAsset,proto3" json:"TargetAsset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferParticipant) Reset()         { *m = OfferParticipant{} }
func (m *OfferParticipant) String() string { return proto.CompactTextString(m) }
func (*OfferParticipant) ProtoMessage()    {}
func (*OfferParticipant) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{8}
}
func (m *OfferParticipant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferParticipant.Unmarshal(m, b)
}
func (m *OfferParticipant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferParticipant.Marshal(b, m, deterministic)
}
func (dst *OfferParticipant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferParticipant.Merge(dst, src)
}
func (m *OfferParticipant) XXX_Size() int {
	return xxx_messageInfo_OfferParticipant.Size(m)
}
func (m *OfferParticipant) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferParticipant.DiscardUnknown(m)
}

var xxx_messageInfo_OfferParticipant proto.InternalMessageInfo

func (m *OfferParticipant) GetSrcHolding() string {
	if m != nil {
		return m.SrcHolding
	}
	return ""
}

func (m *OfferParticipant) GetTargetHolding() string {
	if m != nil {
		return m.TargetHolding
	}
	return ""
}

func (m *OfferParticipant) GetSrcAsset() string {
	if m != nil {
		return m.SrcAsset
	}
	return ""
}

func (m *OfferParticipant) GetTargetAsset() string {
	if m != nil {
		return m.TargetAsset
	}
	return ""
}

type CreateOfferRequest struct {
	Identifier           string              `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Label                string              `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description          string              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Source               *MarketplaceHolding `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target               *MarketplaceHolding `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Rules                []*AssetRule        `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	PrivateKey           string              `protobuf:"bytes,7,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateOfferRequest) Reset()         { *m = CreateOfferRequest{} }
func (m *CreateOfferRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOfferRequest) ProtoMessage()    {}
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{9}
}
func (m *CreateOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOfferRequest.Unmarshal(m, b)
}
func (m *CreateOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOfferRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOfferRequest.Merge(dst, src)
}
func (m *CreateOfferRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOfferRequest.Size(m)
}
func (m *CreateOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOfferRequest proto.InternalMessageInfo

func (m *CreateOfferRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *CreateOfferRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *CreateOfferRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateOfferRequest) GetSource() *MarketplaceHolding {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *CreateOfferRequest) GetTarget() *MarketplaceHolding {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CreateOfferRequest) GetRules() []*AssetRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *CreateOfferRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type CreateOfferResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOfferResponse) Reset()         { *m = CreateOfferResponse{} }
func (m *CreateOfferResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOfferResponse) ProtoMessage()    {}
func (*CreateOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{10}
}
func (m *CreateOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOfferResponse.Unmarshal(m, b)
}
func (m *CreateOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOfferResponse.Marshal(b, m, deterministic)
}
func (dst *CreateOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOfferResponse.Merge(dst, src)
}
func (m *CreateOfferResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOfferResponse.Size(m)
}
func (m *CreateOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOfferResponse proto.InternalMessageInfo

func (m *CreateOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AcceptOfferRequest struct {
	Identifier           string            `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Sender               *OfferParticipant `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             *OfferParticipant `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Count                int64             `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	PrivateKey           string            `protobuf:"bytes,5,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AcceptOfferRequest) Reset()         { *m = AcceptOfferRequest{} }
func (m *AcceptOfferRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptOfferRequest) ProtoMessage()    {}
func (*AcceptOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{11}
}
func (m *AcceptOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptOfferRequest.Unmarshal(m, b)
}
func (m *AcceptOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptOfferRequest.Marshal(b, m, deterministic)
}
func (dst *AcceptOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptOfferRequest.Merge(dst, src)
}
func (m *AcceptOfferRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptOfferRequest.Size(m)
}
func (m *AcceptOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptOfferRequest proto.InternalMessageInfo

func (m *AcceptOfferRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *AcceptOfferRequest) GetSender() *OfferParticipant {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *AcceptOfferRequest) GetReceiver() *OfferParticipant {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *AcceptOfferRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AcceptOfferRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type AcceptOfferResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptOfferResponse) Reset()         { *m = AcceptOfferResponse{} }
func (m *AcceptOfferResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptOfferResponse) ProtoMessage()    {}
func (*AcceptOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{12}
}
func (m *AcceptOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptOfferResponse.Unmarshal(m, b)
}
func (m *AcceptOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptOfferResponse.Marshal(b, m, deterministic)
}
func (dst *AcceptOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptOfferResponse.Merge(dst, src)
}
func (m *AcceptOfferResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptOfferResponse.Size(m)
}
func (m *AcceptOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptOfferResponse proto.InternalMessageInfo

func (m *AcceptOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CloseOfferRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrivateKey           string   `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseOfferRequest) Reset()         { *m = CloseOfferRequest{} }
func (m *CloseOfferRequest) String() string { return proto.CompactTextString(m) }
func (*CloseOfferRequest) ProtoMessage()    {}
func (*CloseOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{13}
}
func (m *CloseOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseOfferRequest.Unmarshal(m, b)
}
func (m *CloseOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseOfferRequest.Marshal(b, m, deterministic)
}
func (dst *CloseOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseOfferRequest.Merge(dst, src)
}
func (m *CloseOfferRequest) XXX_Size() int {
	return xxx_messageInfo_CloseOfferRequest.Size(m)
}
func (m *CloseOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseOfferRequest proto.InternalMessageInfo

func (m *CloseOfferRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CloseOfferRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type CloseOfferResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseOfferResponse) Reset()         { *m = CloseOfferResponse{} }
func (m *CloseOfferResponse) String() string { return proto.CompactTextString(m) }
func (*CloseOfferResponse) ProtoMessage()    {}
func (*CloseOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_fafc1858f841ca71, []int{14}
}
func (m *CloseOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseOfferResponse.Unmarshal(m, b)
}
func (m *CloseOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseOfferResponse.Marshal(b, m, deterministic)
}
func (dst *CloseOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseOfferResponse.Merge(dst, src)
}
func (m *CloseOfferResponse) XXX_Size() int {
	return xxx_messageInfo_CloseOfferResponse.Size(m)
}
func (m *CloseOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseOfferResponse proto.InternalMessageInfo

func (m *CloseOfferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "rpc.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "rpc.CreateAccountResponse")
	proto.RegisterType((*AssetRule)(nil), "rpc.AssetRule")
	proto.RegisterType((*CreateAssetRequest)(nil), "rpc.CreateAssetRequest")
	proto.RegisterType((*CreateAssetResponse)(nil), "rpc.CreateAssetResponse")
	proto.RegisterType((*CreateHoldingRequest)(nil), "rpc.CreateHoldingRequest")
	proto.RegisterType((*CreateHoldingResponse)(nil), "rpc.CreateHoldingResponse")
	proto.RegisterType((*MarketplaceHolding)(nil), "rpc.MarketplaceHolding")
	proto.RegisterType((*OfferParticipant)(nil), "rpc.OfferParticipant")
	proto.RegisterType((*CreateOfferRequest)(nil), "rpc.CreateOfferRequest")
	proto.RegisterType((*CreateOfferResponse)(nil), "rpc.CreateOfferResponse")
	proto.RegisterType((*AcceptOfferRequest)(nil), "rpc.AcceptOfferRequest")
	proto.RegisterType((*AcceptOfferResponse)(nil), "rpc.AcceptOfferResponse")
	proto.RegisterType((*CloseOfferRequest)(nil), "rpc.CloseOfferRequest")
	proto.RegisterType((*CloseOfferResponse)(nil), "rpc.CloseOfferResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketClient interface {
	// create account
	DoCreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// create asset
	DoCreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error)
	// create holding
	DoCreateHolding(ctx context.Context, in *CreateHoldingRequest, opts ...grpc.CallOption) (*CreateHoldingResponse, error)
	DoCreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*CreateOfferResponse, error)
	DoAcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*AcceptOfferResponse, error)
	DoCloseOffer(ctx context.Context, in *CloseOfferRequest, opts ...grpc.CallOption) (*CloseOfferResponse, error)
}

type marketClient struct {
	cc *grpc.ClientConn
}

func NewMarketClient(cc *grpc.ClientConn) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) DoCreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/rpc.market/doCreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) DoCreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error) {
	out := new(CreateAssetResponse)
	err := c.cc.Invoke(ctx, "/rpc.market/doCreateAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) DoCreateHolding(ctx context.Context, in *CreateHoldingRequest, opts ...grpc.CallOption) (*CreateHoldingResponse, error) {
	out := new(CreateHoldingResponse)
	err := c.cc.Invoke(ctx, "/rpc.market/doCreateHolding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) DoCreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*CreateOfferResponse, error) {
	out := new(CreateOfferResponse)
	err := c.cc.Invoke(ctx, "/rpc.market/doCreateOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) DoAcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*AcceptOfferResponse, error) {
	out := new(AcceptOfferResponse)
	err := c.cc.Invoke(ctx, "/rpc.market/doAcceptOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) DoCloseOffer(ctx context.Context, in *CloseOfferRequest, opts ...grpc.CallOption) (*CloseOfferResponse, error) {
	out := new(CloseOfferResponse)
	err := c.cc.Invoke(ctx, "/rpc.market/doCloseOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
type MarketServer interface {
	// create account
	DoCreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// create asset
	DoCreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error)
	// create holding
	DoCreateHolding(context.Context, *CreateHoldingRequest) (*CreateHoldingResponse, error)
	DoCreateOffer(context.Context, *CreateOfferRequest) (*CreateOfferResponse, error)
	DoAcceptOffer(context.Context, *AcceptOfferRequest) (*AcceptOfferResponse, error)
	DoCloseOffer(context.Context, *CloseOfferRequest) (*CloseOfferResponse, error)
}

func RegisterMarketServer(s *grpc.Server, srv MarketServer) {
	s.RegisterService(&_Market_serviceDesc, srv)
}

func _Market_DoCreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).DoCreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.market/DoCreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).DoCreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_DoCreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).DoCreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.market/DoCreateAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).DoCreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_DoCreateHolding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHoldingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).DoCreateHolding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.market/DoCreateHolding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).DoCreateHolding(ctx, req.(*CreateHoldingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_DoCreateOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).DoCreateOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.market/DoCreateOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).DoCreateOffer(ctx, req.(*CreateOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_DoAcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).DoAcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.market/DoAcceptOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).DoAcceptOffer(ctx, req.(*AcceptOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_DoCloseOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).DoCloseOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.market/DoCloseOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).DoCloseOffer(ctx, req.(*CloseOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Market_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "doCreateAccount",
			Handler:    _Market_DoCreateAccount_Handler,
		},
		{
			MethodName: "doCreateAsset",
			Handler:    _Market_DoCreateAsset_Handler,
		},
		{
			MethodName: "doCreateHolding",
			Handler:    _Market_DoCreateHolding_Handler,
		},
		{
			MethodName: "doCreateOffer",
			Handler:    _Market_DoCreateOffer_Handler,
		},
		{
			MethodName: "doAcceptOffer",
			Handler:    _Market_DoAcceptOffer_Handler,
		},
		{
			MethodName: "doCloseOffer",
			Handler:    _Market_DoCloseOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}

func init() { proto.RegisterFile("market.proto", fileDescriptor_market_fafc1858f841ca71) }

var fileDescriptor_market_fafc1858f841ca71 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x4e, 0xdb, 0x4e,
	0x10, 0xc6, 0x31, 0x09, 0x30, 0x01, 0x7e, 0xbf, 0x6e, 0xa1, 0xb8, 0x51, 0x85, 0x22, 0x8b, 0x03,
	0x17, 0x82, 0x48, 0xd5, 0x07, 0x88, 0xe8, 0xa1, 0x7f, 0x54, 0xb5, 0x32, 0x3d, 0xf6, 0xb2, 0xd8,
	0x03, 0x5d, 0xe1, 0xd8, 0x66, 0x77, 0x4d, 0x95, 0xb7, 0xe8, 0xa1, 0xea, 0x9b, 0xf4, 0xda, 0x27,
	0xe8, 0x43, 0x55, 0xde, 0x3f, 0xce, 0xda, 0x09, 0xa4, 0x55, 0x6f, 0x9e, 0xd9, 0x99, 0xd9, 0xef,
	0xfb, 0x66, 0x76, 0x0c, 0xdb, 0x53, 0xca, 0x6f, 0x50, 0x8e, 0x0a, 0x9e, 0xcb, 0x9c, 0xf8, 0xbc,
	0x88, 0xc3, 0x4f, 0xb0, 0x77, 0xce, 0x91, 0x4a, 0x9c, 0xc4, 0x71, 0x5e, 0x66, 0x32, 0xc2, 0xdb,
	0x12, 0x85, 0x24, 0x04, 0xd6, 0x33, 0x3a, 0xc5, 0xc0, 0x1b, 0x7a, 0xc7, 0x5b, 0x91, 0xfa, 0x26,
	0x7b, 0xd0, 0xc5, 0x29, 0x65, 0x69, 0xd0, 0x51, 0x4e, 0x6d, 0x90, 0x01, 0x6c, 0x16, 0x54, 0x88,
	0x2f, 0x39, 0x4f, 0x02, 0x5f, 0x1d, 0xd4, 0x76, 0x78, 0x02, 0xfb, 0xad, 0xea, 0xa2, 0xc8, 0x33,
	0xa1, 0x4a, 0xc9, 0xfc, 0x06, 0x33, 0x53, 0x5f, 0x1b, 0xe1, 0x0b, 0xd8, 0x9a, 0x08, 0x81, 0x32,
	0x2a, 0x53, 0xac, 0x10, 0xc8, 0x59, 0xa1, 0x11, 0x74, 0x23, 0xf5, 0x5d, 0xa5, 0xdd, 0xd1, 0xb4,
	0x44, 0x8b, 0x40, 0x19, 0xe1, 0x57, 0x0f, 0x88, 0xb9, 0x46, 0x65, 0x3f, 0x40, 0x61, 0x08, 0xfd,
	0x04, 0x45, 0xcc, 0x59, 0x21, 0x59, 0x9e, 0x99, 0x32, 0xae, 0x8b, 0x1c, 0x41, 0x97, 0x97, 0x29,
	0x8a, 0xc0, 0x1f, 0xfa, 0xc7, 0xfd, 0xf1, 0xee, 0x88, 0x17, 0xf1, 0xa8, 0x46, 0x15, 0xe9, 0x43,
	0x72, 0x08, 0x50, 0x70, 0x76, 0x47, 0x25, 0xbe, 0xc5, 0x59, 0xb0, 0xae, 0xca, 0x38, 0x9e, 0xf0,
	0x14, 0x1e, 0x37, 0x10, 0x19, 0xda, 0x01, 0x6c, 0x4c, 0x51, 0x08, 0x7a, 0x6d, 0x51, 0x59, 0x33,
	0xfc, 0xe9, 0xd9, 0x46, 0xbc, 0xca, 0xd3, 0x84, 0x65, 0xd7, 0x96, 0xc5, 0x21, 0x00, 0x4b, 0x30,
	0x93, 0xec, 0x8a, 0x21, 0x37, 0x59, 0x8e, 0xa7, 0x92, 0x24, 0xa5, 0x97, 0x58, 0x37, 0x45, 0x19,
	0x55, 0x96, 0x22, 0xa5, 0x69, 0xea, 0xb6, 0x38, 0x9e, 0x2a, 0x8b, 0x56, 0xc8, 0x0c, 0x74, 0x6d,
	0x54, 0xad, 0xbc, 0x2d, 0x69, 0x26, 0x99, 0x9c, 0x05, 0xdd, 0xa1, 0x77, 0xec, 0x47, 0xb5, 0xdd,
	0x62, 0xdc, 0x5b, 0x60, 0x7c, 0x66, 0x5b, 0x5d, 0xe3, 0x5f, 0xc9, 0x39, 0x01, 0xf2, 0x4e, 0x0d,
	0x64, 0x91, 0xd2, 0xd8, 0xe6, 0x91, 0x67, 0xb0, 0xf5, 0x59, 0x7f, 0xbe, 0x4e, 0x4c, 0xc6, 0xdc,
	0xd1, 0x80, 0xd8, 0x69, 0x41, 0xac, 0x49, 0xf9, 0x0e, 0xa9, 0xf0, 0xbb, 0x07, 0xff, 0xbf, 0xbf,
	0xba, 0x42, 0xfe, 0x81, 0x72, 0xc9, 0x62, 0x56, 0xd0, 0x4c, 0xa9, 0x7a, 0xc1, 0x63, 0x73, 0xa5,
	0x55, 0x75, 0xee, 0x21, 0x47, 0xb0, 0xf3, 0x91, 0xf2, 0x6b, 0x94, 0x36, 0x44, 0xab, 0xdb, 0x74,
	0x56, 0x60, 0x2e, 0x78, 0x3c, 0x71, 0xee, 0xac, 0xed, 0x6a, 0xd2, 0x74, 0xf0, 0xc4, 0xd1, 0xd9,
	0x75, 0x85, 0xdf, 0x3a, 0x76, 0x6c, 0x15, 0xbc, 0x7f, 0x6b, 0x78, 0x6b, 0xb0, 0xfd, 0xc5, 0xc1,
	0x3e, 0x85, 0x9e, 0xc8, 0x4b, 0x1e, 0xa3, 0xc2, 0xd2, 0x1f, 0x1f, 0xa8, 0xc9, 0x5e, 0x6c, 0x40,
	0x64, 0xc2, 0xaa, 0x04, 0xa9, 0xe0, 0xaa, 0x59, 0x78, 0x28, 0x41, 0x87, 0xcd, 0x9f, 0x4e, 0xef,
	0xcf, 0x9f, 0xce, 0xc6, 0xfd, 0x4f, 0xc7, 0xa8, 0xb2, 0x72, 0x8c, 0x7e, 0x79, 0x40, 0x26, 0x71,
	0x8c, 0x85, 0xfc, 0x2b, 0x1d, 0x4f, 0xa0, 0x27, 0x30, 0x4b, 0x90, 0x2b, 0x21, 0xfb, 0xe3, 0x7d,
	0x05, 0xb7, 0x3d, 0x29, 0x91, 0x09, 0x22, 0x67, 0xb0, 0xc9, 0x31, 0x46, 0x76, 0x87, 0x5c, 0xa9,
	0x7b, 0x6f, 0x42, 0x1d, 0x56, 0x75, 0x4a, 0x6d, 0x3d, 0x25, 0xb8, 0x1f, 0x69, 0xa3, 0xc5, 0xbf,
	0xbb, 0x8c, 0x7f, 0x83, 0xcd, 0x4a, 0xfe, 0xe7, 0xf0, 0xe8, 0x3c, 0xcd, 0x45, 0x73, 0x8a, 0x76,
	0xa1, 0xc3, 0xec, 0xf3, 0xe9, 0xb0, 0x64, 0xe5, 0xc2, 0x1a, 0x01, 0x71, 0x8b, 0xac, 0xba, 0x74,
	0xfc, 0xc3, 0x87, 0x9e, 0xfe, 0x9b, 0x90, 0x37, 0xf0, 0x5f, 0x92, 0x37, 0xd6, 0x3c, 0x79, 0xaa,
	0xa4, 0x59, 0xf6, 0x63, 0x19, 0x0c, 0x96, 0x1d, 0xe9, 0xeb, 0xc2, 0x35, 0xf2, 0x12, 0x76, 0xea,
	0x5a, 0xea, 0x19, 0x1d, 0xb8, 0xe1, 0xce, 0x76, 0x1f, 0x04, 0x8b, 0x07, 0x75, 0x15, 0x07, 0x91,
	0x7d, 0xaa, 0x2e, 0xa2, 0xe6, 0x86, 0x6d, 0x20, 0x6a, 0x2d, 0xaf, 0x26, 0x22, 0xa5, 0x4d, 0x03,
	0x91, 0x2b, 0x79, 0x03, 0x51, 0x43, 0x46, 0x5b, 0xc5, 0x69, 0xab, 0xa9, 0xb2, 0x38, 0xb6, 0xa6,
	0xca, 0x92, 0x09, 0x08, 0xd7, 0xc8, 0x04, 0xb6, 0x93, 0x7c, 0xde, 0x26, 0xf2, 0x44, 0xdf, 0xd8,
	0x6e, 0xfe, 0xe0, 0x60, 0xc1, 0x6f, 0x4b, 0x5c, 0xf6, 0xd4, 0xbf, 0xff, 0xf9, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0x77, 0xf7, 0xaf, 0x0b, 0x08, 0x00, 0x00,
}
