package transaction

const (
	headerCacheControl                  = "cache-control"
	headerAccept                        = "Accept"
	headerAcceptEncoding                = "Accept-Encoding"
	headerAllow                         = "Allow"
	headerAuthorization                 = "Authorization"
	headerContentDisposition            = "Content-Disposition"
	headerContentEncoding               = "Content-Encoding"
	headerContentLength                 = "Content-Length"
	headerContentType                   = "Content-Type"
	headerCookie                        = "Cookie"
	headerSetCookie                     = "Set-Cookie"
	headerIfModifiedSince               = "If-Modified-Since"
	headerLastModified                  = "Last-Modified"
	headerLocation                      = "Location"
	headerUpgrade                       = "Upgrade"
	headerUserAgent                     = "User-Agent"
	headerVary                          = "Vary"
	headerWWWAuthenticate               = "WWW-Authenticate"
	headerXForwardedProto               = "X-Forwarded-Proto"
	headerXHTTPMethodOverride           = "X-HTTP-Method-Override"
	headerXForwardedFor                 = "X-Forwarded-For"
	headerXRealIP                       = "X-Real-IP"
	headerXRateLimitLimit               = "X-Ratelimit-Limit"
	headerXRateLimitRemainingRequests   = "X-Ratelimit-Remaining"
	headerXRateLimitResetTime           = "X-Ratelimit-Reset"
	headerServer                        = "Server"
	headerOrigin                        = "Origin"
	headerAccessControlRequestMethod    = "Access-Control-Request-Method"
	headerAccessControlRequestHeaders   = "Access-Control-Request-Headers"
	headerAccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	headerAccessControlAllowMethods     = "Access-Control-Allow-Methods"
	headerAccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	headerAccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	headerAccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	headerAccessControlMaxAge           = "Access-Control-Max-Age"

	headerBearer = "Bearer"

	headerXOTP    = "X-OTP"
	headerNoCache = "no-cache"
)
